export const ENV = {
  DATABASE_URL: 'DATABASE_URL',
  PORT: 'PORT',
  JWT_SECRET: 'JWT_SECRET',
  CLOUDINARY: {
    CLOUD_NAME: 'CLOUDINARY_CLOUD_NAME',
    API_KEY: 'CLOUDINARY_API_KEY',
    API_SECRET: 'CLOUDINARY_API_SECRET',
  },
};
